[workspace]
authors = ["PÃ¤r Larsson <par.larsson@umu.se>"]
channels = ["conda-forge", "bioconda"]
name = "vicon"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.10"
samtools = "*"
bcftools = "*"
bwa = "*"
bwa-mem2 = "*"
minimap2 = "*"
strobealign = "*"
bowtie2 = ">=2.5.4,<3"
picard = "*"
ivar = "*"
spades = "*"
megahit = "*"
mafft = "*"
mash = "*"
pandas = "*"
biopython = "*"
snakemake = "*"
fastp = "*"
iqtree = ">=2"
matplotlib = "*"
